#!/bin/bash

# Helper functions for Dotfies Manager
#
# This file contains a bunch of helper functions for installing files and
# directories using the Dotfiles Manager script.
#
# Author: Darshit Shah  <darnir@gmail.com>
# License: MIT

# This helper function gets the location of where the configuration file should
# exist on the system based on the keywords passed to it. Supported keywords
# are:
#   * etc: Attempts to store the file in the user's /etc directory. The command
#   should be executed with superuser privileges. TODO: Automatically set
#   SUDO when the location is /etc
#   * home: Stores the file in the user's $HOME dir with a dot (.) affixed to
#   the filename.
#   * userconf: Stored the file in the user's configuration directory, i.e.
#   ~/.config/.
#   * bin: Symlink the file in the /usr/local/bin/ directory. TODO:
#   Automatically set SUDO when location is bin
#   * systemd-user: Attempts to install the file as a unit file in the systemd
#   user configuration directory, ~/.config/systemd/user/. TODO: Automatically
#   set the file to to create a hardlink when installing a systemd unit file
#   * autostart: Install the file to ~/.config/autostart.
#   If none of the above keywords are provided, the parameter is assumed to
#   contain the absolute path to the directory where the file should be
#   installed.
_get_conf_file() {
    local confpath
    case "$1" in
        etc) confpath="/etc/";;
        home) confpath="$HOME/.";;
        userconf) confpath="$HOME/.config/";;
        bin) confpath="/usr/local/bin/";;
        systemd-user) confpath="$HOME/.config/systemd/user/";;
        autostart) confpath="$HOME/.config/autostart/";;
        *) confpath="$1/"
    esac
	mkdir -p "$confpath"
	confpath="${confpath}${_CONF_NAME}"
    echo "$confpath"
}

_check_sudo() {
    if [[ $1 == true ]]
    then
        echo "sudo"
    else
        echo ""
    fi
}

_set_linktype() {
    if [[ -z $1 || $1 == true ]]
    then
        echo "-s "
    else
        echo ""
    fi
}

_test_source_file() {
    log_info "Checking if ${_CONF_NAME} exists in package"
    if [ ! -f "${_LOC_FILE}" ]
    then
        log_warn "Source file not found. Will create empty symlink"
    fi
}

_backup_target() {
    log_info "Checking if ${_CONF_FILE} exists"
    if [ -f "${_CONF_FILE}" ]
    then
        _BACKUPNAME="${_BCK_FILE}"
        _BCKNO=1
        while [ -f "${_BACKUPNAME}" ]; do
            _BACKUPNAME="${_BCK_FILE}.${_BCKNO}"
            _BCKNO=$((_BCKNO+1))
        done
        log_info "Target file found, saving to ${_BACKUPNAME}"
        if [ -L "${_CONF_FILE}" ]
        then
            REAL_CONF=$(realpath "${_CONF_FILE}")
            ${SUDO} cp -R "${REAL_CONF}" "${_BACKUPNAME}"
            ${SUDO} rm "${_CONF_FILE}"
        else
            ${SUDO} mv "${_CONF_FILE}" "${_BACKUPNAME}"
        fi
    else
        ${SUDO} rm "${_CONF_FILE}" 2>/dev/null || true
        log_info "Target file not found"
    fi
}

_backup_target_dir() {
    log_info "Checking if ${_CONF_DIR} exists"
    if [ -d "${_CONF_DIR}" ]
    then
        log_info "Target directory found, saving to ${_BCK_DIR}"
        $SUDO mv -v "${_CONF_DIR}" "${_BCK_DIR}"
    else
        log_info "Target directory not found"
    fi
}

_log_installed() {
    local srcfile="$1"
    local dstfile="$2"
    local lnktype="$3"

    if [[ $lnktype == '-s ' ]]; then
        echo -e "  * $srcfile\t->  $dstfile" >> "$TEMPDB"
    else
        echo -e "  * $srcfile\t--> $dstfile" >> "$TEMPDB"
    fi
}

_real_install() {
	local sudo="$1"
	local linktype="$2"
	local loc_file="$3"
	local conf_file="$4"

    # TODO: Test if the linktype is possible. Else fallback to a copy and warn
    # user about it.
	#
	# Shellcheck gives a warning here asking to doublequote the linktype
	# variable. However, that will break the ln command since the variable may
	# be empty sometimes. Doublequoting will pass an empty parameter to ln
	# causing the command to fail.
    ${sudo} ln ${linktype}"${loc_file}" "${conf_file}"
}

_begin_install() {
	log_all_n "white" "Installing: "
	log_all_n "nc" "$(eval printf "%-15s" "$1")"
	log_std ""
}

_end_install() {
    _log_installed "$_LOC_FILE" "$_CONF_FILE" "$linktype"
	log_all "green" "[Done]"
}

# Function: install_file()
# Parameter List:
#   $1 : Conf File Name
#   $2 : Install Path for Conf File
#   $3 : Needs root privileges to install?
#   $4 : Is a symlink? (Default: Yes)
install_file() {
	_begin_install "$@"
    local _CONF_NAME="$1"
    local _CONF_FILE=$(_get_conf_file "$2")
    local _BCK_FILE=${_CONF_FILE}.bck
    local _LOC_FILE=$(pwd)/Packages/${PACKAGE_NAME}/${_CONF_NAME}

    local SUDO=$(_check_sudo "$3")
    local linktype=$(_set_linktype "$4")

    _test_source_file
    _backup_target

    log_info "Linking dotfile ${_CONF_NAME} to ${_CONF_FILE}"
	_real_install "${SUDO}" "${linktype}" "${_LOC_FILE}" "${_CONF_FILE}"
	_end_install
}

# TODO: Use a param to end_install to cause a yellow warning or red failed
# output
install_private_file() {
	_begin_install "$@"
    local _CONF_NAME="$1"
    local _CONF_FILE=$(_get_conf_file "$2")
    local _BCK_FILE=${_CONF_FILE}.bck
    local _LOC_FILE="/media/truecrypt1/${_CONF_NAME}"

    local SUDO=$(_check_sudo "$3")
    local linktype=$(_set_linktype "$4")

    log_info "Checking if ${_LOC_FILE} is mounted"
    if [[ ! -f "${_LOC_FILE}" ]]
    then
        log_warn "Private configuration file not found."
        log_info "Will continue and create symlink to location"
    else
        _backup_target
    fi

    log_info "Linking dotfile ${_CONF_NAME} to ${_CONF_FILE}"
	_real_install "${SUDO}" "${linktype}" "${_LOC_FILE}" "${_CONF_FILE}"
	_end_install
}

install_directory() {
	_begin_install "$@"
    local _CONF_NAME="$1"
    local _CONF_DIR=$(_get_conf_file "$2")
    local _BCK_DIR=${_CONF_DIR}bck
    local _LOC_DIR=$(pwd)/Packages/${PACKAGE_NAME}/${_CONF_NAME}

    local SUDO=$(_check_sudo "$3")
    local linktype=$(_set_linktype "$4")

    _backup_target_dir

    _info "Linking directory ${_CONF_NAME} to ${_CONF_DIR}"
	_real_install "${SUDO}" "${linktype}" "${_LOC_FILE}" "${_CONF_FILE}"
	_end_install
}

depends() {
    ./dotfiles -b "$PACKAGE_NAME" -d "$1"
}


################################################################################
# Custom Functions for use by the dotfile package installers                   #
################################################################################

install_packages() {
	if ! isarchlinux; then
		log_warn "System is not ArchLinux. Packages not installed."
		log_info "Please install $* manually"
		return
	fi

	sudo pacman -S $*
}

install_aur() {
    if ! isarchlinux; then
		log_warn "System is not ArchLinux. Packages not installed."
		log_info "Please install $1 manually"
		return
	fi

    # We are in Arch Linux
    echo "Installing $1 from AUR"
    pushd /tmp
    wget https://aur.archlinux.org/cgit/aur.git/snapshot/"$1".tar.gz
    tar -xvzf "$1".tar.gz
    pushd "$1"
    makepkg -si
    popd
    popd
}
safetouch() {
    if [ ! -f "$1" ]
    then
        _info "Touching $1"
        touch "$1"
    else
        _info "$1 exists, not touching"
    fi
}

is_in_path() {
    exec_name="$1"
    if ! which "$exec_name" &> /dev/null; then
        return 1
    else
        return 0
    fi
}

isarchlinux() {
    _info "Checking if current system is Arch Linux..."
    if which pacman &> /dev/null
    then
        _info "System is Arch Linux. Continuing..."
        return 0
    else
        _warn "System is not Arch Linux."
        return 1
    fi
}
