# Modified Commands
#alias diff='vimdiff'
alias grep='grep --color=auto'
alias less='less -r'
alias more='less'
alias df='df -h'
alias du='du -c -h'
alias mkdir='mkdir -p -v'
alias nano='vim'
alias ping='ping -c 5'
alias ls='ls --color'
alias rm='rm -v'
alias vi="vim"

# New Commands
alias da='date "+%A, %B %d, %Y [%T]"'
alias du1='du --max-depth=1'
alias hist='history | grep'      # requires an argument
alias openports='netstat --all --numeric --programs --inet --inet6'
alias la='ls -la'
alias :q='exit'
alias :wq='exit'
alias aur='cower -ddfu --target=/home/sauron/builds/'
alias alert='beep -f 5000 -l 60 -r 2'
alias configwget='time ./configure --enable-option-checking --disable-silent-rules --enable-dependency-tracking --with-ssl=openssl --without-included-regex --enable-nls -C CFLAGS="-g -O0 -Wall -Wextra"'
alias parallelconfig='configwget --enable-metalink --enable-threads=posix'
alias run='time ./runTest.py'
alias proj='cd ~/Programming/wget/'
alias resetproj='./bootstrap --skip-po && configwget'
alias resetprojpar='./bootstrap --skip-po && parallelconfig'
alias gitignore='git status --porcelain | grep '^??' | cut -c4- >>.gitignore'
alias cleantex='rm *.{aux,bbl,blg,log,lot,out,toc,pdf,dvi} 2>/dev/null'
alias vimup='vim +PluginUpdate'
alias mirrorlist='reflector --save /etc/pacman.d/mirrorlist --sort rate --verbose'

# Safety Features
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

# Allows one to use bash aliases with superuser permissions. See bash(1) for
# details
alias sudo='sudo '
